name: spirit
base: core18
version: '0.2.0'
summary: Spirit Desktop Mascot of the Twenty First Century
description: |
  Spirit is a modern and hackable desktop mascot, it operates very similar to
  MaCoPix and Shimeji but was never invented to replace either of them. 
  Spirit is made just out of curiousity and as an alternative to both of them since
  both are legacy software Spirit is built from the ground up using Qt Framework and C++, 
  uses rust for it's auxilary tools and helper applications. Spirit is also cross-platform
  and can run in all the major platforms with no issues.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  spirit:
    common-id: com.github.antony-jr.spirit
    command: spirit
    plugs:
      - kde-frameworks-5-plug
      - home
      - opengl
      - network
      - network-bind
      - pulseaudio

parts:
  spirit:
    plugin: nil
